workflows:
  android-build:
    name: Android Build
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
